### ISSUE TITLE
Crash reports stopped loading.

### ISSUE THREAD

**Issue by SefoNotasi** [asherkin/accelerator#17]
I haven't tracked exactly when it happened, but this year all crash reports stopped uploading to crash.limetech.org.

 SourceMod  accelerator.log:
`Presubmit failed: Failed to connect to 2a01:7e00::f03c:91ff:fe96:6d6b: Unknown error 101 (7)
Failed to upload crash dump: Failed to connect to 2a01:7e00::f03c:91ff:fe96:6d6b: Unknown error 101 (7)
Presubmit failed: Failed to connect to 2a01:7e00::f03c:91ff:fe96:6d6b: Unknown error 101 (7)
Failed to upload crash dump: Failed to connect to 2a01:7e00::f03c:91ff:fe96:6d6b: Unknown error 101 (7)
Presubmit failed: Failed to connect to 2a01:7e00::f03c:91ff:fe96:6d6b: Unknown error 101 (7)
Failed to upload crash dump: Failed to connect to 2a01:7e00::f03c:91ff:fe96:6d6b: Unknown error 101 (7)
Presubmit failed: Failed to connect to 2a01:7e00::f03c:91ff:fe96:6d6b: Unknown error 101 (7)
Failed to upload crash dump: Failed to connect to 2a01:7e00::f03c:91ff:fe96:6d6b: Unknown error 101 (7)
`

SourceMod  errors_20240828.log:
`L 08/28/2024 - 13:26:37: SourceMod error session started
L 08/28/2024 - 13:26:37: Info (map "c14m2_lighthouse") (file "/game/left4dead2/addons/sourcemod/logs/errors_20240828.log")
L 08/28/2024 - 13:26:37: [CRASH] Accelerator failed to upload crash dump: Failed to connect to 2a01:7e00::f03c:91ff:fe96:6d6b: Unknown error 101 (7)
L 08/28/2024 - 14:46:23: Error log file session closed.`

Dedicated linux server with the latest versions of SourceMod, MetaMod and Accelerator. 

Maybe the problem is that crash reports are uploaded from Russian hosting, where the server is located? (server IP: 46.174.50.10:27268).

**Comment by asherkin** [comment]
This appears to be a problem with your host's IPv6 connectivity combined with SourceMod's libcurl version being from 2008 and not having proper fallback to IPv4 support (added in 2013).

I've removed the AAAA (IPv6) record for `crash.limetech.org` so it should start working again in about a day or so.
